# Generated by Django 4.0.3 on 2022-12-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_rename_employee_nummber_salesperson_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
