# Generated by Django 4.0.3 on 2022-12-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_number',
            field=models.IntegerField(unique=True),
        ),
    ]
