# Generated by Django 4.0.3 on 2022-12-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_appointment_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='reason',
        ),
    ]
