# Generated by Django 4.0.3 on 2022-12-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='owner',
            new_name='customer',
        ),
    ]
