# Generated by Django 4.0.3 on 2022-12-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_rename_owner_appointment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='automobile',
        ),
    ]
