# Generated by Django 4.0.3 on 2022-12-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0015_alter_appointment_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('reason', models.CharField(max_length=250)),
                ('vip', models.BooleanField(default=False)),
                ('vin', models.CharField(max_length=17, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentHistory', to='service_rest.technician')),
            ],
        ),
    ]
