# Generated by Django 4.0.3 on 2022-12-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0016_appointmenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentHistory',
        ),
    ]
